import type { Metadata } from "next";
import { outfit, instrumentalSans } from "../components/ui/fonts";
import { clashDisplay } from "../components/ui/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} ${instrumentalSans.variable} ${clashDisplay}`}
      >
        <main className="min-h-screen bg-white flex items-center justify-center">
          {children}
        </main>
      </body>
    </html>
  );
}
